# Generated by Django 2.1.3 on 2019-01-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190127_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-id',), 'verbose_name': '成员'},
        ),
        migrations.AddField(
            model_name='member',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='member',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
